#!/bin/sh

# Get the list of changed files
changed_files=$(git diff --name-only HEAD HEAD~1)

# Check if any of the changed files are in the ./GameClient/GameClientApi/ directory
if echo "$changed_files" | grep -q "^GameClient/GameClientApi/"; then
    # Change the working directory to the test project directory
    cd "../GameClient/GameClientApiTests"

    # Print the current directory and the list of files in it
    pwd
    ls

    # Run the tests
    dotnet test --no-restore

    # Check the exit status of the 'dotnet test' command
    if [ $? -ne 0 ]; then
        echo "Tests failed!"
        exit 1
    fi

    # If we got here, the tests passed.
    echo "Tests passed!"
fi

exit 0