#!/bin/sh

echo "Current working directory: $(pwd)"

# Get the list of changed files
changed_files=$(git diff --name-only HEAD HEAD~1)

# Print the list of changed files
echo "Changed files:"
echo "$changed_files"

# Check if any of the changed files are in the ./GameClient/GameClientApi/ directory
if echo "$changed_files" | grep -q "^GameClient/GameClientApiTests/"; then
    echo "Changes detected in GameClient/GameClientApiTests/"

    # Change the working directory to the test project directory
    cd "GameClient/GameClientApiTests"

    dotnet restore

    # Run the tests
    dotnet test --no-restore

    # Check the exit status of the 'dotnet test' command
    if [ $? -ne 0 ]; then
        echo "Tests failed!"
        exit 1
    fi

    # If we got here, the tests passed.
    echo "Tests passed!"
else
    echo "No changes detected in GameClient/GameClientApiTests/"
fi

exit 0